In [1]:
import pandas as pd
import numpy as np

In [2]:
mi_primer_vector = np.array([2,7,2,1,9,10,-1])

In [ ]:
np.round(np.mean(mi_primer_vector),2)

np.float64(4.29)

In [ ]:
np.max(mi_primer_vector)

np.int64(10)

In [ ]:
mi_primer_vector

array([ 2,  7,  2,  1,  9, 10, -1])

In [3]:
calificaciones = np.array([7.5, 9.0, 6.5, 8.5, 10.0, 5.5, 8.0, 9.5])
calificaciones

array([ 7.5,  9. ,  6.5,  8.5, 10. ,  5.5,  8. ,  9.5])

In [4]:
len(calificaciones)

8

In [5]:
calificaciones[0]

np.float64(7.5)

In [6]:
calificaciones[2]

np.float64(6.5)

In [8]:
### Quiero lo que hay en el último lugar del vector
calificaciones[len(calificaciones)-1]

np.float64(9.5)

In [9]:
calificaciones[-1]

np.float64(9.5)

In [10]:
calificaciones

array([ 7.5,  9. ,  6.5,  8.5, 10. ,  5.5,  8. ,  9.5])

In [11]:
calificaciones[1:3]  # él entiende que le estoy pidiendo posición 1 y posición 2

array([9. , 6.5])

In [13]:
calificaciones[1:4] # él entiende que le estoy pidiendo posición 1 y posición 2 y posición 3

array([9. , 6.5, 8.5])

In [14]:
calificaciones[0:2]

array([7.5, 9. ])

In [15]:
calificaciones[3:]

array([ 8.5, 10. ,  5.5,  8. ,  9.5])

In [18]:
calificaciones[2:-1]

array([ 6.5,  8.5, 10. ,  5.5,  8. ])

In [19]:
calificaciones[:5]

array([ 7.5,  9. ,  6.5,  8.5, 10. ])

In [23]:
calificaciones

array([ 7.5,  9. ,  6.5,  8.5, 10. ,  5.5,  8. ,  9.5])

In [24]:
# quiero las posisiones 1,2, 4,6
calificaciones[[1,2,4,6]]

array([ 9. ,  6.5, 10. ,  8. ])

In [27]:
calificaciones

array([ 7.5,  9. ,  6.5,  8.5, 10. ,  5.5,  8. ,  9.5])

In [26]:
calificaciones > 7

array([ True,  True, False,  True,  True, False,  True,  True])

In [28]:
calificaciones[calificaciones > 7]

array([ 7.5,  9. ,  8.5, 10. ,  8. ,  9.5])

In [30]:
not False

True

In [35]:
~(calificaciones > 7) #virgulilla

array([False, False,  True, False, False,  True, False, False])

In [36]:
calificaciones[~(calificaciones > 7)]

array([6.5, 5.5])

In [41]:
## Quiero las calificaciones debajo del promedio
promedio = np.mean(calificaciones)
calificaciones[calificaciones <= promedio]



array([7.5, 6.5, 5.5, 8. ])

In [42]:
# Tiro un dado 10 veces y obtengo como resultados: 5, 6, 3, 2,6, 4, 1, 4, 5, 4
#  Cuántas veces se obtuvo un múltiplo de 3?

lanzamientos = np.array([5, 6, 3, 2,6, 4, 1, 4, 5, 4])
lanzamientos

array([5, 6, 3, 2, 6, 4, 1, 4, 5, 4])

In [49]:
len(lanzamientos[(lanzamientos == 3) | (lanzamientos == 6)])

3

In [54]:
# Operador residuo
9 % 3

0

In [58]:
len(lanzamientos[lanzamientos % 3 == 0])

3

In [64]:
np.sum(lanzamientos % 3 == 0)

np.int64(3)

In [65]:
# Ejemplo práctico para probabilidad
#Se obtuvieron estos resultados 1, 3, 5, 2, 6, 1, 4, 3, 6, 2, 5, 1
resultados = np.array([1, 3, 5, 2, 6, 1, 4, 3, 6, 2, 5, 1])
resultados

array([1, 3, 5, 2, 6, 1, 4, 3, 6, 2, 5, 1])

In [66]:
#Primer lanzamiento
resultados[0]

np.int64(1)

In [67]:
# Últimos 3 lanzamientos
n = len(resultados)
resultados[n-3:]

array([2, 5, 1])

In [69]:
resultados[-3:]

array([2, 5, 1])

In [79]:
# Lanzamientos que fueron 6
np.sum(resultados == 6)

np.int64(2)

In [80]:
#Proporción de unos

100 * np.sum(resultados == 1) / len(resultados)


np.float64(25.0)

In [84]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [-2,5,8]])

In [85]:
M

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [-2,  5,  8]])

In [86]:
M.shape

(4, 3)

In [90]:
M.shape[1]

3